// <auto-generated />
using System;
using Lofi_Spot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lofi_Spot.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20211117232754_Migrations")]
    partial class Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lofi_Spot.Dominio.Carritos", b =>
                {
                    b.Property<int>("CarritoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCarritoID")
                        .HasColumnType("int");

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.HasKey("CarritoID");

                    b.HasIndex("NumeroCarritoID");

                    b.HasIndex("ProductoID");

                    b.ToTable("Carritos");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Categorias", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.DetalleDeCompras", b =>
                {
                    b.Property<int>("DetalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NumeroCarritoID")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DetalleID");

                    b.HasIndex("NumeroCarritoID");

                    b.ToTable("DetalleDeCompras");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Direcciones", b =>
                {
                    b.Property<int>("DireccionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CP")
                        .HasColumnType("int");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DireccionID");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.NumeroCarritos", b =>
                {
                    b.Property<int>("NumeroCarritoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("NumeroCarritoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("NumeroCarritos");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Productos", b =>
                {
                    b.Property<int>("ProductoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagenes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Producto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductoID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Roles", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Tarjetas", b =>
                {
                    b.Property<int>("TarjetaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CVV")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("TarjetaID");

                    b.ToTable("Tarjetas");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Usuarios", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DireccionID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nick")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<int>("TarjetaID")
                        .HasColumnType("int");

                    b.HasKey("UsuarioID");

                    b.HasIndex("DireccionID");

                    b.HasIndex("RolID");

                    b.HasIndex("TarjetaID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Carritos", b =>
                {
                    b.HasOne("Lofi_Spot.Dominio.NumeroCarritos", "NumeroCarrito")
                        .WithMany("Carritos")
                        .HasForeignKey("NumeroCarritoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lofi_Spot.Dominio.Productos", "Producto")
                        .WithMany("Carritos")
                        .HasForeignKey("ProductoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NumeroCarrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.DetalleDeCompras", b =>
                {
                    b.HasOne("Lofi_Spot.Dominio.NumeroCarritos", "NumeroCarrito")
                        .WithMany("DetalleDeCompras")
                        .HasForeignKey("NumeroCarritoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NumeroCarrito");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.NumeroCarritos", b =>
                {
                    b.HasOne("Lofi_Spot.Dominio.Usuarios", "Usuario")
                        .WithMany("NumeroCarritos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Productos", b =>
                {
                    b.HasOne("Lofi_Spot.Dominio.Categorias", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Usuarios", b =>
                {
                    b.HasOne("Lofi_Spot.Dominio.Direcciones", "Direccion")
                        .WithMany("Usuarios")
                        .HasForeignKey("DireccionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lofi_Spot.Dominio.Roles", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lofi_Spot.Dominio.Tarjetas", "Tarjeta")
                        .WithMany("Usuarios")
                        .HasForeignKey("TarjetaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");

                    b.Navigation("Rol");

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Categorias", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Direcciones", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.NumeroCarritos", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("DetalleDeCompras");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Productos", b =>
                {
                    b.Navigation("Carritos");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Roles", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Tarjetas", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Lofi_Spot.Dominio.Usuarios", b =>
                {
                    b.Navigation("NumeroCarritos");
                });
#pragma warning restore 612, 618
        }
    }
}
